package uascrud;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class uasFormMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form uasFormMainMenu
     */
    public uasFormMainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_pg_produksi = new javax.swing.JButton();
        btn_pg_marketing = new javax.swing.JButton();
        btn_pg_personalia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_pg_produksi.setText("Divisi Produksi");
        btn_pg_produksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pg_produksiActionPerformed(evt);
            }
        });

        btn_pg_marketing.setText("Divisi Marketing");
        btn_pg_marketing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pg_marketingActionPerformed(evt);
            }
        });

        btn_pg_personalia.setText("Divisi Personalia");
        btn_pg_personalia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pg_personaliaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("E-Inventori Office");

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_pg_personalia, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pg_marketing, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pg_produksi, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_logout)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(btn_pg_marketing, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(btn_pg_produksi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btn_pg_personalia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pg_produksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pg_produksiActionPerformed
        // TODO add your handling code here:
        try{
            uasFormProduksi pro = new uasFormProduksi();
            pro.setVisible(true);
            this.setVisible(false);
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_pg_produksiActionPerformed

    private void btn_pg_marketingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pg_marketingActionPerformed
        // TODO add your handling code here:
        try{
            uasFormMarketing mar = new uasFormMarketing();
            mar.setVisible(true);
            this.setVisible(false);
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_pg_marketingActionPerformed

    private void btn_pg_personaliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pg_personaliaActionPerformed
        // TODO add your handling code here:
        try{
            uasFormPersonalia per = new uasFormPersonalia();
            per.setVisible(true);
            this.setVisible(false);
        }catch(SQLException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_pg_personaliaActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        uasLogin bb = new uasLogin();
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan Logout?","Warning",2)== JOptionPane.YES_OPTION){
            bb.Logout(uasSession.getUserID());
            uasFormLogin m = new uasFormLogin();
            m.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_pg_marketing;
    private javax.swing.JButton btn_pg_personalia;
    private javax.swing.JButton btn_pg_produksi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
