package uascrud;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class uasFormPersonalia extends javax.swing.JFrame {
    private DefaultTableModel tabmode;
    private ResultSet hasil;
    
    uasCrudPersonalia aa = new uasCrudPersonalia();
    
    public uasFormPersonalia() throws SQLException{
        initComponents();
        tampil_database();
    }
    
    public void tampil_database(){
        Object [] baris = {"ID Barang","Nama Barang","Tgl Masuk Barang","Jumlah Barang","Harga Satuan Barang","Harga Total Barang","Jumlah Barang Tersedia","Jumlah Barang Away","Tgl Keluar Barang"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_marketing.setModel(tabmode);
        try {
            hasil = aa.tampilData();
            while(hasil.next()){
                aa.setIdBarang(hasil.getString("idBarang"));
                aa.setNamaBarang(hasil.getString("namaBarang"));
                aa.setTglMasuk(hasil.getString("tglMasuk"));
//                aa.setJumlahBarang(hasil.getString("jumlahBarang"));
//                aa.setHargaSatuan(hasil.getString("hargaSatuan"));
//                aa.setHargaTotal(hasil.getString("hargaTotal"));
                aa.setJumlahBarang(hasil.getDouble("jumlahBarang"));
                aa.setHargaSatuan(hasil.getDouble("hargaSatuan"));
//                aa.setHargaTotal(hasil.getDouble("harga_total"));
                aa.setHargaTotal(hasil.getDouble("jumlahBarang"), hasil.getDouble("hargaSatuan"));
//                aa.setHargaTotal();
                aa.setBarangHadir(hasil.getDouble("barangHadir"));
                aa.setBarangAway(hasil.getDouble("jumlahBarang"), hasil.getDouble("barangHadir"));
                aa.setTglKeluar(hasil.getString("tglKeluar"));
                
//                aa.setID(hasil.getString("id"));
//                aa.setNama(hasil.getString("nama"));
//                aa.setAlamat(hasil.getString("alamat"));
                String[] data = {aa.getIdBarang(), aa.getNamaBarang(), aa.getTglMasuk(), Double.toString(aa.getJumlahBarang()), Double.toString(aa.getHargaSatuan()), Double.toString(aa.getHargaTotal()), Double.toString(aa.getBarangHadir()), Double.toString(aa.getBarangAway()), aa.getTglKeluar()};
//                String[] data = {aa.getIdBarang(), aa.getNamaBarang(), aa.getTglMasuk(), aa.getJumlahBarang(), aa.getHargaSatuan(), aa.getHargaTotal(), aa.barangHadir, aa.barangAway, aa.getTglKeluar()};
                tabmode.addRow(data);
            }
        } catch (Exception e){
            
        }
    }
    
    
    public void reset_text(){
        txt_id.setText("");
        txt_nm.setText("");
        txt_msk.setText("");
        txt_jml.setText("");
        txt_hst.setText("");
        txt_htl.setText("");
        txt_bts.setText("");
        txt_bwy.setText("");
        txt_klr.setText("");
    }
    
    public void reset_cari(){
        txt_cari.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_ubah = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_cari = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_smdt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_total = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nm = new javax.swing.JTextField();
        txt_msk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_marketing = new javax.swing.JTable();
        txt_jml = new javax.swing.JTextField();
        txt_hst = new javax.swing.JTextField();
        txt_htl = new javax.swing.JTextField();
        txt_bts = new javax.swing.JTextField();
        txt_bwy = new javax.swing.JTextField();
        txt_klr = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_item = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_hitung = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_htwy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Tgl Masuk Barang");

        jLabel5.setText("Jumlah Barang");

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jLabel6.setText("Harga Satuan Barang");

        jLabel7.setText("Harga Total Barang");

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        jLabel8.setText("Jumlah Barang Tersedia");

        btn_cari.setText("Cari Data");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        jLabel9.setText("Jumlah Barang Away");

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Barang");

        btn_smdt.setText("Semua Data");
        btn_smdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_smdtActionPerformed(evt);
            }
        });

        jLabel10.setText("Tgl Keluar Barang");

        btn_back.setText("Kembali");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_total.setText("Total");
        btn_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_totalActionPerformed(evt);
            }
        });

        jLabel11.setText("Pencarian");

        jLabel12.setText("Jumlah Item Inventori");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Inventori Divisi Personalia");

        txt_nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nmActionPerformed(evt);
            }
        });

        tabel_marketing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_marketing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_marketingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_marketing);

        txt_klr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_klrActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Barang");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_hitung.setText("Hitung");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        btn_htwy.setText("Hitung");
        btn_htwy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_htwyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_nm, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_msk, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10))
                                                .addGap(39, 39, 39)
                                                .addComponent(txt_klr, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(jLabel11)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txt_bts, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txt_bwy, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btn_htwy)))
                                                        .addGap(0, 0, Short.MAX_VALUE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_jml, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_hst, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_htl, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(606, 606, 606))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_back)
                        .addGap(931, 931, 931)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_smdt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_item, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hitung)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_back)
                    .addComponent(jLabel1)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari)
                    .addComponent(btn_smdt)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txt_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hitung))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bwy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(btn_htwy))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_msk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_klr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_jml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_hst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_htl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(btn_total))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simpan)
                            .addComponent(btn_reset)
                            .addComponent(btn_ubah)
                            .addComponent(btn_hapus)
                            .addComponent(btn_keluar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        if (txt_id.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, ID Barang belum diisi !");
            txt_id.requestFocus();
        } else if (txt_nm.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Nama Barang belum diisi !");
            txt_nm.requestFocus();
        } else if (txt_msk.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Tanggal Masuk Barang belum diisi !");
            txt_msk.requestFocus();
        } else if (txt_jml.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang belum diisi !");
            txt_jml.requestFocus();
        } else if (txt_hst.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Harga Satuan Barang belum diisi !");
            txt_hst.requestFocus();
        } else if (txt_htl.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Harga Total Barang belum diisi !");
            txt_htl.requestFocus();
        } else if (txt_bts.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang Tersedia belum diisi !");
            txt_bts.requestFocus();
        } else if (txt_bwy.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang Away belum diisi !");
            txt_bwy.requestFocus();
        } else if (txt_klr.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Tanggal Keluar Barang belum diisi !");
            txt_klr.requestFocus();
        } else {
            try{
                aa.setIdBarang(txt_id.getText());
                aa.setNamaBarang(txt_nm.getText());
                aa.setTglMasuk(txt_msk.getText());
                aa.setJumlahBarang(Double.parseDouble(txt_jml.getText()));
                aa.setHargaSatuan(Double.parseDouble(txt_hst.getText()));
                //                aa.setHargaTotal(Double.parseDouble(txt_htl.getText()));
                //                aa.setHargaTotal();
                aa.setHargaTotal(Double.parseDouble(txt_jml.getText()), Double.parseDouble(txt_jml.getText()));
                aa.setBarangHadir(Double.parseDouble(txt_bts.getText()));
                aa.setBarangAway(Double.parseDouble(txt_jml.getText()), Double.parseDouble(txt_bts.getText()));
                aa.setTglKeluar(txt_klr.getText());

                aa.ubahData(aa.getIdBarang(), aa.getNamaBarang(), aa.getTglMasuk(), aa.getJumlahBarang(), aa.getHargaSatuan(), aa.getHargaTotal(), aa.getBarangHadir(), aa.getBarangAway(), aa.getTglKeluar());

                JOptionPane.showMessageDialog(null, "Data berhasil diubah" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal diubah" , "Informasi",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed

        Object [] baris = {"ID Barang","Nama Barang","Tgl Masuk Barang","Jumlah Barang","Harga Satuan Barang","Harga Total Barang","Jumlah Barang Tersedia","Jumlah Barang Away","Tgl Keluar Barang"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_marketing.setModel(tabmode);
        try {
            hasil = aa.cariData(txt_cari.getText());
            while(hasil.next()){
                aa.setIdBarang(hasil.getString("idBarang"));
                aa.setNamaBarang(hasil.getString("namaBarang"));
                aa.setTglMasuk(hasil.getString("tglMasuk"));
                aa.setJumlahBarang(hasil.getDouble("jumlahBarang"));
                aa.setHargaSatuan(hasil.getDouble("hargaSatuan"));
                aa.setHargaTotal(hasil.getDouble("jumlahBarang"), hasil.getDouble("hargaSatuan"));
                aa.setBarangHadir(hasil.getDouble("barangHadir"));
                aa.setBarangAway(hasil.getDouble("jumlahBarang"), hasil.getDouble("barangHadir"));
                aa.setTglKeluar(hasil.getString("tglKeluar"));
                String[] data = {aa.getIdBarang(), aa.getNamaBarang(), aa.getTglMasuk(), Double.toString(aa.getJumlahBarang()), Double.toString(aa.getHargaSatuan()), Double.toString(aa.getHargaTotal()), Double.toString(aa.getBarangHadir()), Double.toString(aa.getBarangAway()), aa.getTglKeluar()};
                tabmode.addRow(data);
            }
            JOptionPane.showMessageDialog(null,"Data berhasil ditemukan!");
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        if (txt_id.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, ID belum diisi !");
            txt_id.requestFocus();
        } else {
            if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus dataini ?","Warning",2) == JOptionPane.YES_OPTION){
                String id = "";
                try {
                    aa.setIdBarang(txt_id.getText());
                    aa.hapusData(aa.getIdBarang());
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus" , "Informasi",JOptionPane.INFORMATION_MESSAGE);
                    tampil_database();
                    reset_text();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus" , "Informasi",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_smdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_smdtActionPerformed
        // TODO add your handling code here:
        Object [] baris = {"ID Barang","Nama Barang","Tgl Masuk Barang","Jumlah Barang","Harga Satuan Barang","Harga Total Barang","Jumlah Barang Tersedia","Jumlah Barang Away","Tgl Keluar Barang"};
        tabmode = new DefaultTableModel(null, baris);
        tabel_marketing.setModel(tabmode);
        try {
            hasil = aa.tampilData();
            while(hasil.next()){
                aa.setIdBarang(hasil.getString("idBarang"));
                aa.setNamaBarang(hasil.getString("namaBarang"));
                aa.setTglMasuk(hasil.getString("tglMasuk"));
                aa.setJumlahBarang(hasil.getDouble("jumlahBarang"));
                aa.setHargaSatuan(hasil.getDouble("hargaSatuan"));
                aa.setHargaTotal(hasil.getDouble("jumlahBarang"), hasil.getDouble("hargaSatuan"));
                aa.setBarangHadir(hasil.getDouble("barangHadir"));
                aa.setBarangAway(hasil.getDouble("jumlahBarang"), hasil.getDouble("barangHadir"));
                aa.setTglKeluar(hasil.getString("tglKeluar"));
                String[] data = {aa.getIdBarang(), aa.getNamaBarang(), aa.getTglMasuk(), Double.toString(aa.getJumlahBarang()), Double.toString(aa.getHargaSatuan()), Double.toString(aa.getHargaTotal()), Double.toString(aa.getBarangHadir()), Double.toString(aa.getBarangAway()), aa.getTglKeluar()};
                tabmode.addRow(data);
            }
            reset_cari();
        } catch (Exception e){
        }
    }//GEN-LAST:event_btn_smdtActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
                uasFormMainMenu m = new uasFormMainMenu();
                m.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_totalActionPerformed
        // TODO add your handling code here:
        if (txt_jml.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang belum diisi !");
            txt_jml.requestFocus();
        } else if (txt_hst.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Harga Satuan Barang belum diisi !");
            txt_hst.requestFocus();
        } else{
            String jml = txt_jml.getText();
            Double jumlah = Double.parseDouble(jml);
            String hst = txt_hst.getText();
            Double satuan = Double.parseDouble(hst);
            aa.setHargaTotal(jumlah, satuan);
            txt_htl.setText(String.valueOf(aa.getHargaTotal()));
        }
    }//GEN-LAST:event_btn_totalActionPerformed

    private void txt_nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nmActionPerformed

    private void tabel_marketingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_marketingMouseClicked
        // TODO add your handling code here:
        try{
            int row = tabel_marketing.rowAtPoint(evt.getPoint());

            //             "ID Barang","Nama Barang","Tgl Masuk Barang","Jumlah Barang","Harga Satuan Barang","Harga Total Barang","Jumlah Barang Tersedia","Jumlah Barang Keluar","Tgl Keluar Barang"
            String idBarang = tabel_marketing.getValueAt(row, 0).toString();
            String namaBarang = tabel_marketing.getValueAt(row, 1).toString();
            String tgl_masuk = tabel_marketing.getValueAt(row, 2).toString();

            String jumlah_barang = tabel_marketing.getValueAt(row, 3).toString();
            String harga_satuan = tabel_marketing.getValueAt(row, 4).toString();
            String harga_total = tabel_marketing.getValueAt(row, 5).toString();

            String barang_hadir = tabel_marketing.getValueAt(row, 6).toString();
            String barang_away = tabel_marketing.getValueAt(row, 7).toString();
            String tgl_keluar = tabel_marketing.getValueAt(row, 8).toString();

            txt_id.setText(String.valueOf(idBarang));
            txt_nm.setText(String.valueOf(namaBarang));
            txt_msk.setText(String.valueOf(tgl_masuk));
            txt_jml.setText(String.valueOf(jumlah_barang));
            txt_hst.setText(String.valueOf(harga_satuan));
            txt_htl.setText(String.valueOf(harga_total));
            txt_bts.setText(String.valueOf(barang_hadir));
            txt_bwy.setText(String.valueOf(barang_away));
            txt_klr.setText(String.valueOf(tgl_keluar));
        }catch(Exception e){
        }
    }//GEN-LAST:event_tabel_marketingMouseClicked

    private void txt_klrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_klrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_klrActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if (txt_id.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, ID Barang belum diisi !");
            txt_id.requestFocus();
        } else if (txt_nm.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Nama Barang belum diisi !");
            txt_nm.requestFocus();
        } else if (txt_msk.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Tanggal Masuk Barang belum diisi !");
            txt_msk.requestFocus();
        } else if (txt_jml.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang belum diisi !");
            txt_jml.requestFocus();
        } else if (txt_hst.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Harga Satuan Barang belum diisi !");
            txt_hst.requestFocus();
        } else if (txt_htl.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Harga Total Barang belum diisi !");
            txt_htl.requestFocus();
        } else if (txt_bts.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang Tersedia belum diisi !");
            txt_bts.requestFocus();
        } else if (txt_bwy.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang Away belum diisi !");
            txt_bwy.requestFocus();
        } else if (txt_klr.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Tanggal Keluar Barang belum diisi !");
            txt_klr.requestFocus();
        } else {
            try {
                aa.setIdBarang(txt_id.getText());
                aa.setNamaBarang(txt_nm.getText());
                aa.setTglMasuk(txt_msk.getText());
                aa.setJumlahBarang(Double.parseDouble(txt_jml.getText()));
                aa.setHargaSatuan(Double.parseDouble(txt_hst.getText()));
                aa.setHargaTotal(Double.parseDouble(txt_jml.getText()), Double.parseDouble(txt_jml.getText()));
                aa.setBarangHadir(Double.parseDouble(txt_bts.getText()));
                aa.setBarangAway(Double.parseDouble(txt_jml.getText()), Double.parseDouble(txt_bts.getText()));
                aa.setTglKeluar(txt_klr.getText());
                aa.simpanData(aa.getIdBarang(), aa.getNamaBarang(), aa.getTglMasuk(), aa.getJumlahBarang(), aa.getHargaSatuan(), aa.getHargaTotal(), aa.getBarangHadir(), aa.getBarangAway(), aa.getTglKeluar());
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal tersimpan" , "Informasi",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        try {
            hasil = aa.hitungData();
            if(hasil.next()){
                String count = hasil.getString("count(*)");
                txt_item.setText(count);
            }
        } catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar ?","Warning",2)== JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_htwyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_htwyActionPerformed
        // TODO add your handling code here:
        if (txt_bts.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Maaf, Jumlah Barang belum diisi !");
            txt_bts.requestFocus();
        } else{
            String brg = txt_jml.getText();
            Double jumlahBarang = Double.parseDouble(brg);

            String ada = txt_bts.getText();
            Double hadir = Double.parseDouble(ada);

            aa.setBarangAway(jumlahBarang, hadir);
            //            aa.setHargaTotal();
            txt_bwy.setText(String.valueOf(aa.getBarangAway()));
        }
    }//GEN-LAST:event_btn_htwyActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_htwy;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_smdt;
    private javax.swing.JButton btn_total;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_marketing;
    private javax.swing.JTextField txt_bts;
    private javax.swing.JTextField txt_bwy;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_hst;
    private javax.swing.JTextField txt_htl;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_item;
    private javax.swing.JTextField txt_jml;
    private javax.swing.JTextField txt_klr;
    private javax.swing.JTextField txt_msk;
    private javax.swing.JTextField txt_nm;
    // End of variables declaration//GEN-END:variables
}
